{
	"version": 1635388653,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/letter-sheet0.png",
		"images/letter-sheet1.png",
		"images/btnreplay-sheet0.png",
		"images/life-sheet0.png",
		"images/life-sheet1.png",
		"images/explosion-sheet0.png",
		"images/screenlose-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/titleimage-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/screenchange-sheet0.png",
		"images/laser-sheet0.png",
		"images/screenlaser-sheet0.png",
		"images/tableend-sheet0.png",
		"images/tableini-sheet0.png",
		"images/titlesubimage-sheet0.png",
		"images/textscore.png",
		"images/textcombo.png",
		"images/textend.png",
		"media/hit confirmbeep.m4a",
		"media/hit confirmbeep.ogg",
		"media/lose sawing.m4a",
		"media/lose sawing.ogg",
		"media/change mod cancel - 5.m4a",
		"media/change mod cancel - 5.ogg",
		"media/click menu click 3.m4a",
		"media/click menu click 3.ogg",
		"media/laser ok - 5.m4a",
		"media/laser ok - 5.ogg",
		"media/blue space v0_8(foxsynergy).m4a",
		"media/blue space v0_8(foxsynergy).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}